AllCops:   
  Exclude:     
    - '.metadata/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false
